# Generated by Django 2.2.4 on 2019-08-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='siteUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=200)),
                ('karma', models.BigIntegerField()),
                ('regDate', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
