# Generated by Django 2.2.4 on 2019-08-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_siteusers_regdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='rssPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='siteusers',
            name='karma',
            field=models.IntegerField(),
        ),
    ]
