# Generated by Django 2.2.4 on 2019-08-19 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20190818_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteusers',
            name='karma',
        ),
    ]
