# Generated by Django 2.2.4 on 2019-08-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20190819_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteusers',
            name='login',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
