# Generated by Django 2.2.4 on 2019-08-23 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20190823_1051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userReactions',
        ),
    ]
